version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.32
